### ISSUE TITLE
Move schema and LDIF files to oms-core project

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-development-vm#26]
I have the feeling that these files do not belong to the VM. One indicator is that you are modifying them frequently. This is not in itself a problem, but I guess that these changes should be done in sync with some changes that you do in the other projects... What do you think, @serviceman?

**Comment by serviceman** [comment]
If the schema changes, and if puppet is configured correctly, the dev only needs a "git pull" from oms-core and not from both repositories....

While I don't think the files belong to the other project, the advantage is clear. Before moving though, I would prefer to wait and think more about it

**Comment by serviceman** [comment]
Ok, I am convinced. You will probably have to make the repository be cloned first, and then the files found there - it is the only thing that requires a bit of time (but you already know puppet so it will be trivial).

I will put the files in a folder called schema on the root of the oms-core project, the content will be [as is now](https://github.com/AEGEE/oms-development-vm/tree/master/puppet/modules/aegee_ldap/files)

**Comment by serviceman** [comment]
closed by ad5f431, I don't know why it wasn't automatically updated (only the first issue was)
