### ISSUE TITLE
Document how to integrate a new microservice

### ISSUE THREAD

**Issue by linuxbandit** [AEGEE/oms-development-vm#51]
@blacksph3re did well but in the end he fell at the point of having a file here

https://github.com/AEGEE/oms-development-vm/tree/master/puppet/modules/aegee_oms_modules/files/etc/init

Document such that it's clear what is needed

**Comment by blacksph3re** [comment]
What I did until now:
1. Clone repo
2. Modify vagrant file, c&p oms-core and modify with common sense
3. Modify /puppet/manifest/site.pp
4. copy oms-development-vm/puppet/modules/aegee_oms_modules/files/etc/init/oms-core.conf, name as your service is named (some broken service needs it to do nothing with it)
5. Add your autostart routine to a tmux session in runall.sh
6. vagrant up
